"""
Django settings for project25 project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import pymysql

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------
# Umgebungsvariblen Management
# ------------------------------

# Methode 1 mit Python Dotenv
# -----------------------------
from dotenv import load_dotenv
# Lädt die Variablen aus der .env-Datei in die Umgebung 
load_dotenv() 

# Methode 2 mit Django Environ
# -----------------------------
import environ
# Initialisiere environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Lese die .env-Datei (BASE_DIR muss korrekt definiert sein)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Unsicher weil in Code
# SECRET_KEY = 'django-insecure--kdsl4gr_@t3)!6!ajg0be56ov=0kj=!wq7esdv96@wxf=m+#7'

# Methode 1 mit Dotenv
# SECRET_KEY = os.environ.get('SECRET_KEY')

# Methode 2 mit Django Environ
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Custom Apps
    'start',
    'wednesday',
    'get_examples',
    'models_examples',
    'models_relations',
    'weather',
    'bia_forms',
    'accounts',
    'movies',
    
    # Default Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project25.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project25.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default SQLite3 Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MySQL Database Settings
pymysql.install_as_MySQLdb()

# Unsicher Variante, da Daten sichtbar im Code stehen
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'django_nov_25_db',
#         'USER': 'django_nov_25_user',
#         'PASSWORD': 'user_password_sehr_sicher',
#         'HOST': '127.0.0.1',
#         'PORT': '3307',
#     }
# }

# Bessere Variante mit Umgebungsvariablen
#------------------------------------------
# Variante 1 (allgemein für Python) - Dotenv
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.environ.get('DB_NAME'),
#         'USER': os.environ.get('DB_USER'),
#         'PASSWORD': os.environ.get('DB_PASSWORD'),
#         'HOST': os.environ.get('DB_HOST'),
#         'PORT': os.environ.get('DB_PORT'),
#     }
# }

# Variante 2 (speziell für Django) - Django Environ
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': env('DB_NAME'),
#         'USER': env('DB_USER'),
#         'PASSWORD': env('DB_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env('DB_PORT'),
#     }
# }

#-------------------------------
# POSTGRESQL EXAMPLE
#-------------------------------
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'nov_postgres_db',
#         'USER': 'nov_postgres_user',
#         'PASSWORD': 'user_password_sehr_sicher',
#         'HOST': '127.0.0.1',
#         'PORT': '5433',
#     }
# }

# Variante 2 sogar noch besser 
# Die Datenbank-URL wird automatisch in die korrekte Dictionary-Struktur geparst
# DATABASES = {
#     'default': env.db(),
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# HIER wird der projektweite static-Ordner hinzugefügt
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = Path(__file__).resolve().parent.parent.parent/'all_staticfiles'

# Mediafiles settings
# Physical place of the media files
MEDIA_ROOT = BASE_DIR / 'mediafiles' # oder os.path.join(BASE_DIR, 'mediafiles')

# 'Fake' URL of the Media
MEDIA_URL = '/uwe-ochsenknecht/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------
# Session Management
# -------------------
# Session settings
SESSION_COOKIE_AGE = 1209600  # Two weeks in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Session expires when the browser is closed


# ----------------------------
# Sonstige Umgebungsvariablen
# ----------------------------
# WEATHER_API = os.environ.get('WEATHER_API')
WEATHER_API = env('WEATHER_API')