# Generated by Django 5.2.8 on 2025-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(verbose_name='Frequenz (MHz)')),
                ('signal_type', models.CharField(choices=[('noise', 'Hintergrundrauschen'), ('pulsar', 'Pulsar'), ('intelligent', 'Intelligenter Ursprung'), ('unknown', 'Unbekannt / Bedrohlich')], max_length=20, verbose_name='Signal-Typ')),
                ('intensity', models.IntegerField(verbose_name='Signalstärke (dB)')),
                ('received_date', models.DateField(verbose_name='Empfangsdatum')),
                ('decoded_message', models.TextField(blank=True, null=True, verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
