# Generated by Django 5.2.8 on 2025-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Vollständiger Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Kontakt-Frequenz')),
                ('codename', models.CharField(choices=[('falcon', 'Falcon'), ('shadow', 'Shadow'), ('viper', 'Viper'), ('ghost', 'Ghost')], max_length=20, verbose_name='Codename')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Dienstjahre')),
                ('special_skills', models.TextField(verbose_name='Besondere Fähigkeiten')),
                ('agrees_to_memory_wipe', models.BooleanField(default=False, verbose_name='Zustimmung Gedächtnislöschung')),
            ],
        ),
    ]
