# Generated by Django 5.2.8 on 2025-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia_forms', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Artefakt-Bezeichnung')),
                ('discovery_date', models.DateField(verbose_name='Funddatum')),
                ('origin_sector', models.CharField(max_length=50, verbose_name='Ursprungssektor')),
                ('threat_level', models.CharField(choices=[('low', 'Niedrig (Sicher)'), ('medium', 'Mittel (Vorsicht geboten)'), ('high', 'Hoch (Eindämmung erforderlich)'), ('critical', 'Kritisch (Weltuntergangsszenario)')], default='medium', max_length=10, verbose_name='Bedrohungsstufe')),
                ('is_radioactive', models.BooleanField(default=False, verbose_name='Strahlung aktiv?')),
                ('description', models.TextField(verbose_name='Beschreibung der Anomalie')),
            ],
        ),
    ]
