# Generated by Django 5.2.8 on 2025-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia_forms', '0003_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='origin_sector',
            field=models.CharField(max_length=50),
        ),
    ]
