# Generated by Django 5.2.8 on 2025-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bia_forms', '0004_alter_artifact_origin_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='origin_sector',
            field=models.CharField(max_length=50, verbose_name='Ursprungssektor'),
        ),
    ]
