# Generated by Django 5.2.8 on 2025-11-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Filmtitel')),
                ('year', models.PositiveIntegerField(verbose_name='Erscheinungsjahr')),
                ('director', models.CharField(max_length=150, verbose_name='Regie')),
                ('lead_actor', models.CharField(max_length=150, verbose_name='Hauptdarsteller:in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Filmplakat')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filme',
                'ordering': ['-created_at'],
            },
        ),
    ]
