# Generated by Django 5.2.8 on 2025-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Eigene Videodatei'),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='z.B. https://www.youtube.com/watch?v=dQw4w9WgXcQ', null=True, verbose_name='YouTube URL'),
        ),
    ]
