# Generated by Django 5.2.8 on 2025-11-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_video_file_movie_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='z.B. https://www.youtube.com/watch?v=dQw4w9WgXcQ', max_length=500, null=True, verbose_name='YouTube URL'),
        ),
    ]
