# Generated by Django 5.2.8 on 2025-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name des Maklers'),
        ),
    ]
