# Generated by Django 5.2.8 on 2025-11-14 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_examples', '0002_alter_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel des Exposés')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preis immer in Euro angeben.', max_digits=12, verbose_name='Preis (in EUR)')),
                ('bedrooms', models.IntegerField(default=1, verbose_name='Schlafzimmer')),
                ('bathrooms', models.FloatField(default=1.0, verbose_name='Badezimmer')),
                ('property_type', models.CharField(choices=[('house', 'Haus'), ('apartment', 'Wohnung'), ('land', 'Grundstück')], default='apartment', max_length=10, verbose_name='Immobilientyp')),
                ('status', models.CharField(choices=[('for_sale', 'Zum Verkauf'), ('sold', 'Verkauft'), ('draft', 'Entwurf (nicht veröffentlicht)')], default='draft', max_length=10, verbose_name='Status')),
                ('listed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
            ],
        ),
    ]
