# Generated by Django 5.2.8 on 2025-11-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_examples', '0003_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': 'Makler', 'verbose_name_plural': 'Makler'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': 'listed_date', 'ordering': ['-updated_at'], 'verbose_name': 'Immobilie', 'verbose_name_plural': 'Immobilien'},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('title', 'address')},
        ),
        migrations.AlterModelTable(
            name='property',
            table='immobilien_angebote',
        ),
    ]
