# Generated by Django 5.2.8 on 2025-11-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_examples', '0004_alter_agent_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='immobilien_makler',
        ),
    ]
