# Generated by Django 5.2.8 on 2025-11-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_examples', '0005_alter_agent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hobby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
