# Generated by Django 5.2.8 on 2025-11-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
