# Generated by Django 5.2.8 on 2025-11-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_relations', '0003_person_passport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passport',
            table='passport',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
