# Generated by Django 5.2.8 on 2025-11-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_relations', '0005_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='models_relations.student'),
        ),
    ]
