# Generated by Django 5.2.8 on 2025-11-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_relations', '0007_category_product_between_category_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='between',
            table='m2m-between',
        ),
        migrations.AlterModelTable(
            name='category',
            table='m2m-category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='m2m-product',
        ),
    ]
